### ISSUE TITLE
Docs: 添加__cron__说明

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/koishi-plugin-cron#1]
文档中应当说明使用本插件需要using \_\_cron__
搜索了一下github，有三个甚至四个using了cron， 一个__cron__都没有，显然是文档的锅x

顺便，这样的写法非常反直觉，不知有什么从cordis出发的improvement可以考虑？

**Comment by shigma** [comment]
你说的对，之后可能重构 API 发 2.0 版本。
